const FETCH = "FETCH";
const GET_RESSOURCES = "GET_RESSOURCES";
const SEARCH = "SEARCH";
const SUCCESS_SEARCH = "SUCCESS_SEARCH";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const SUCCESS = "SUCCESS";
const ERROR = "ERROR";
const RESET_STATE = "RESET_STATE";

export {
  FETCH,
  GET_RESSOURCES,
  SEARCH,
  SUCCESS_SEARCH,
  UPDATE,
  DELETE,
  SUCCESS,
  ERROR,
  RESET_STATE,
};
