# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: d8e12af41f7aae15662a75b73a2609a89936d9e3
      with:
        args: 
          -Dsonar.organization=anthonyroyer16
          -Dsonar.projectKey=AnthonyRoyer16_CubeReact
          -Dsonar.sources=.
